# -*- encoding : utf-8 -*-
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
  belongs_to :user
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: authorizations
#
# * id         :integer         not null
#   provider   :string(255)
#   user_id    :integer
#   uid        :string(255)
#   created_at :datetime        not null
#   updated_at :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
